### ISSUE TITLE
Cannot install on Fedora 26/27 using Python 3.6

### ISSUE THREAD

**Issue by ppitonak** [ludbb/secp256k1-py#22]
Run `docker build -t foo .` for this Dockerfile:

```
FROM fedora:27
RUN  dnf install -y gcc automake autoconf pkg-config libtool python3-devel \
    libffi-devel openssl-devel redhat-rpm-config 
RUN pip3 install --user secp256k1
CMD echo "Hi!"
```

Result:

```
    /tmp/pip-build-p8qbm3sp/secp256k1/libsecp256k1/src/ecmult_impl.h:230:5: note: include ‘<string.h>’ or provide a declaration of ‘memset’
    /tmp/pip-build-p8qbm3sp/secp256k1/libsecp256k1/src/tests.c: In function ‘test_ecdsa_der_parse’:
    /tmp/pip-build-p8qbm3sp/secp256k1/libsecp256k1/src/tests.c:3702:52: error: dereferencing pointer to incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
             valid_openssl = !BN_is_negative(sig_openssl->r) && !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 && BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 && BN_num_bits(sig_openssl->s) <= 256;
                                                        ^~
    make: *** [Makefile:1048: src/tests-tests.o] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-p8qbm3sp/secp256k1/setup.py", line 295, in <module>
        "Topic :: Security :: Cryptography"
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 555, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-p8qbm3sp/secp256k1/setup.py", line 217, in run
        subprocess.check_call(["make"], cwd=build_temp)
      File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
```

**Comment by pch957** [comment]
seems you don't have command 'make'
try install make

**Comment by ppitonak** [comment]
`make` is available. It seems that this package cannot be installed using Python 3.6 (default) but it works with 3.5

**Comment by Wallacoloo** [comment]
I can confirm this bug on Arch Linux. Installing this library via pip on Python3.5 succeeds, presumably because it uses a *prebuilt* package as stated in the Readme, but installing via pip on Python3.6 triggers a build of the C library which fails as shown above by @ppitonak.

```
$ gcc --version
gcc (GCC) 7.2.1 20171224
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

To highlight the build error:
```
    /tmp/pip-build-p8qbm3sp/secp256k1/libsecp256k1/src/tests.c: In function ‘test_ecdsa_der_parse’:
    /tmp/pip-build-p8qbm3sp/secp256k1/libsecp256k1/src/tests.c:3702:52: error: dereferencing pointer to incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
             valid_openssl = !BN_is_negative(sig_openssl->r) && !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 && BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 && BN_num_bits(sig_openssl->s) <= 256;
```

I wouldn't be surprised if it's somehow tied to us using a newer version of gcc than the libsecp256k1 devs which handles this error differently.

**Comment by Uxio0** [comment]
I see that there are recompiled binary wheels available for Python 2.7, 3.3, 3.4, and 3.5 on Linux. Would be awesome to have it too for Python 3.6

**Comment by xjia1** [comment]
Please see https://github.com/ludbb/secp256k1-py/issues/24#issuecomment-397505150 for a workaround.
